spring:
  application:
    name: erp-hrms-backend
  datasource:
    url: jdbc:mysql://localhost:3306/hrms_db
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
